# Generated by Django 5.2.1 on 2025-05-20 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamecanica', '0004_mechanic_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('em_analise', 'Em análise'), ('pendente', 'Pendente'), ('concluido', 'Concluído')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='appointments', to='agendamecanica.mechanic')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='appointments', to='agendamecanica.service')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='appointments', to='agendamecanica.vehicle')),
            ],
            options={
                'db_table': 'agendamentos',
                'unique_together': {('mechanic', 'appointment_datetime')},
            },
        ),
    ]
