# Generated by Django 5.2.1 on 2025-05-20 18:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamecanica', '0005_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, help_text='Descrição geral do orçamento ou observações do mecânico', null=True)),
                ('total', models.DecimalField(decimal_places=2, help_text='Valor total do orçamento', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='enviado', help_text='Status atual do orçamento', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(help_text='Agendamento relacionado ao orçamento', on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='agendamecanica.appointment')),
            ],
            options={
                'db_table': 'orcamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_personalizado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='agendamecanica.budget')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='budget_items', to='agendamecanica.service')),
            ],
            options={
                'db_table': 'itens_orcamento',
            },
        ),
    ]
