# Generated by Django 5.2.1 on 2025-05-20 19:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamecanica', '0006_budget_budgetitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_realizacao', models.DateField(auto_now_add=True)),
                ('valor_cobrado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('appointment', models.OneToOneField(blank=True, help_text='Agendamento original do serviço, se houver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_history', to='agendamecanica.appointment')),
                ('mechanic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_realizados', to='agendamecanica.mechanic')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos', to='agendamecanica.service')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_servicos', to='agendamecanica.vehicle')),
            ],
            options={
                'db_table': 'historico_servicos',
                'ordering': ['-data_realizacao'],
            },
        ),
    ]
