# Generated by Django 5.2.1 on 2025-05-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamecanica', '0008_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanic',
            name='specialties',
        ),
        migrations.AddField(
            model_name='mechanic',
            name='specialties',
            field=models.ManyToManyField(blank=True, help_text='Selecione as categorias em que o mecânico é especializado.', to='agendamecanica.category'),
        ),
    ]
