# Generated by Django 5.2.1 on 2025-06-04 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamecanica', '0009_remove_mechanic_specialties_mechanic_specialties'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='nova_data_servico',
            field=models.DateField(blank=True, help_text='Nova data sugerida para execução de serviços adicionais, se necessário', null=True),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='preco_personalizado',
            field=models.DecimalField(decimal_places=2, help_text='Preço específico para esse serviço/peça', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterModelTable(
            name='budgetitem',
            table=None,
        ),
    ]
