# Generated by Django 5.2.1 on 2025-06-05 14:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamecanica', '0010_budget_nova_data_servico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='preco_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor final cobrado pelo serviço (caso não haja orçamento)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='agendamecanica.appointment'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='nova_data_servico',
            field=models.DateField(blank=True, help_text='Nova data sugerida para execução de serviços adicionais', null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='enviado', max_length=20),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='preco_personalizado',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
