# Generated by Django 5.2.1 on 2025-06-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamecanica', '0011_appointment_preco_final_alter_budget_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Apenas mecânicos aprovados aparecerão para agendamento e poderão prestar serviços.'),
        ),
    ]
