# Generated by Django 5.2.1 on 2025-06-09 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamecanica', '0013_relatoriodummy_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('Enviado', 'Enviado'), ('Aprovado', 'Aprovado'), ('Recusado', 'Recusado')], default='enviado', max_length=20),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='agendamecanica.budget'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='preco_personalizado',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agendamecanica.service'),
        ),
    ]
