# Generated by Django 5.2.1 on 2025-06-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamecanica', '0014_alter_budget_status_alter_budgetitem_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='agendamento_executado',
            field=models.BooleanField(default=False),
        ),
    ]
