# Generated by Django 5.2.1 on 2025-06-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamecanica', '0015_budget_agendamento_executado'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='valor_cobrado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
